### ISSUE TITLE
Upgrade node-forge to 0.10.0 - in 2.0.4 release

### ISSUE THREAD

**Issue by kidplug** [googleapis/google-p12-pem#297]
In light of new advisory:

High          │ Prototype Pollution in node-forge 
https://npmjs.com/advisories/1561

**Comment by kidplug** [comment]
Current package.json:

```
  "dependencies": {
    "node-forge": "^0.9.0"
  },
```

Semantic versioning for major "0" ignores the caret ^ :(

**Comment by sofisl** [comment]
I'm sorry, premature close! I was confused by the PR earlier.

**Comment by kidplug** [comment]
This doesn't fix the issue in the google-p12-pem@2.0.4 release

**Comment by stephenplusplus** [comment]
My PR unintentionally closed this issue. I don't know if we want to go back and address this in the 2.0.0 release-- are you unable to upgrade to ^3.0?

**Comment by kidplug** [comment]
We'd prefer to not upgrade all these libs at this time.
The dependency tree is this:

```
└─┬ @google-cloud/speech@3.6.0
  └─┬ @google-cloud/common@2.4.0
    └─┬ google-auth-library@5.10.1
      └─┬ gtoken@4.1.4
        └─┬ google-p12-pem@2.0.4
          └── node-forge@0.9.2

```

As far as I can tell, 3.6.0 is still a "current" release of google cloud speech; likewise for all the other packages shown.
The only package in that last which is not a "current" release is node-forge.

I would expect any "current" releases to apply dependency upgrades when a "HIGH" npm advisory is issued:
High │ Prototype Pollution in node-forge
https://npmjs.com/advisories/1561

**Comment by stephenplusplus** [comment]
I'm currently working through a similar tree here: https://github.com/googleapis/nodejs-logging/issues/904#issuecomment-704339095. Eventually, Speech (the ^4.x releases) will get a new release once the others are updated.

cc @JustinBeckwith for the concerns regarding the release process.

**Comment by stephenplusplus** [comment]
@kidplug Going back in a previous release line to make the fix is possible, but ideally, you could upgrade to make sure you're protected going forward. Is there anything we can do to help the upgrade process? Did the change to speech@4 involve any breaking changes that are difficult to include in your app/environment?

**Comment by kidplug** [comment]
I'll try the google speech v4 upgrade.  Initially testing seems fine.

**Comment by bcoe** [comment]
@kidplug did the upgrade go okay for you? I'm debating today whether or not we need to back-port fixes to the 5.x version of auth.

**Comment by kidplug** [comment]
Yes, our application ran fine on the upgraded speech library.  Planning to commit the upgrade in our upcoming release.

**Comment by staadecker** [comment]
@bcoe I would personally would really enjoy a back-port fix to at least 2.0.2 since the `firebase-tools` package [depends on 2.0.2](https://github.com/firebase/firebase-tools/blob/e567ae99d691ea06d8d90f4891cab88547149320/package-lock.json#L6199) and isn't able to update to the latest version (see [here](https://github.com/firebase/firebase-tools/issues/2671), they don't want to drop support to Node 8). A back-port to versions 2.0.2 and 2.0.4 would resolve the issue. `firebase-tools` has over 1 million monthly downloads.

Thank you!

**Comment by sofisl** [comment]
@bcoe, given that this would involve back-porting a fix, and that we are not currently (though we do plan to) provide ongoing support to these versions in the future, I'm relabeling this issue as a process. We can (eventually) try out Java's new tooling for these types of requests.

**Comment by chingor13** [comment]
Backported to v2.0.5 in #345
